apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc-claim
  labels:
   app: vprodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: default
  
